version: "3.9"

services:
  ai-service:
    build: .
    image: ai-microservice:dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    # Later you can mount models:
    # volumes:
    #   - ./models:/app/ai_service/models